//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class District2
    {
        public int ID { get; set; }
        public string Name1 { get; set; }
        public Nullable<int> House_id { get; set; }
    
        public virtual houses2 houses2 { get; set; }
    }
}
